create table BRANDS(
    ID BIGINT AUTO_INCREMENT,
    NAME VARCHAR(255),
    PRIMARY KEY (ID)
);

create table PRODUCT_PRICES(
    ID BIGINT AUTO_INCREMENT,
    BRAND_ID BIGINT,
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    PRICE_LIST INTEGER,
    PRODUCT_ID BIGINT,
    PRIORITY INTEGER,
    PRICE NUMERIC(20, 2),
    CURR VARCHAR(20),
    PRIMARY KEY (ID),
    FOREIGN KEY (BRAND_ID) REFERENCES BRANDS(ID)
);